### ISSUE TITLE
Consumir la lista de comunidades directo de Github.

### ISSUE THREAD

**Issue by GusGA** [Villanuevand/openve-cli#5]
Actulmente se consume de un servicio externo que debe actualizarce en función del [repo](https://github.com/OpenVE/comunidades-en-telegram) de open-ve.
a.
¿Es posible que se pueda consumir directo de github a tráves de su api pública? Para así consultar la lista y que esta esté siempre actualizada.

OJO.

A menos que este servicio se actualice de la lista, si es así pueden cerrar esta issue y ya.

**Comment by Villanuevand** [comment]
Hola @GusGA,

La data que de muestra es dinámica.  Cree un scrapper que lee la información directamente del readme del repositorio de Openve-comunidades. 

Todo esto es expuesto gracias a un Cloud functions de Firebase y que puedes encontrar la URL de la misma en el servicio OpenVe...

**Comment by GusGA** [comment]
Ah genial entonces.
